two.checkForInput(pygame.mouse.get_pos())
            three.checkForInput(pygame.mouse.get_pos())
            four.checkForInput(pygame.mouse.get_pos())
            five.checkForInput(pygame.mouse.get_pos())
            six.checkForInput(pygame.mouse.get_pos())
            seven.checkForInput(pygame.mouse.get_pos())
            eight.checkForInput(pygame.mouse.get_pos())
            nine.checkForInput(pygame.mouse.get_pos())